In [3]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# 1



In [14]:
neg_arr = a[a < 0]

neg_arr

array([-2, -1, -6, -7])

# 2

In [31]:
pos_arr = a[a >= 0]

pos_arr.shape

(8,)

# 3

In [32]:
pos_arr = a[a >= 0]

pos_arr[pos_arr % 2 == 0]



array([ 4, 10, 12,  0,  0,  0])

# 4

In [26]:
plus_three_arr = a + 3

print(a)
print(plus_three_arr)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


In [29]:
 answer = plus_three_arr[plus_three_arr > 0]

answer.shape

(10,)

# 5

In [5]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [39]:
sq_a = a ** 2

print(sq_a.mean())

print(sq_a.std())

74.0
144.0243035046516


# 6

In [42]:
cen_val = a.mean()

centered = a - cen_val


print(a)
print(cen_val)
print(centered)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
3.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


# 7


In [7]:
import scipy.stats as stats

zscores = stats.zscore(a)

print(zscores)


[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


# 8

In [62]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

arr = np.array(a)


In [63]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(arr)

print(sum_of_a)

55


In [64]:

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(arr)
print(min_of_a)


1


In [65]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(arr)




In [66]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(arr)



In [67]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.prod(arr)

product_of_a

3628800

In [68]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = arr ** 2

print(squares_of_a)

[  1   4   9  16  25  36  49  64  81 100]


In [70]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = arr[arr % 2 == 1]

print(odds_in_a)

[1 3 5 7 9]


In [71]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = arr[arr % 2 == 0]

evens_in_a


array([ 2,  4,  6,  8, 10])

# part 2

In [73]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

brr = np.array(b)

sums = np.sum(brr)
print(sums)



33


In [89]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in brr:
    sum_of_b += sum(row)
    
print(sum_of_b)

print(np.sum(brr))


33
33


In [90]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(brr[0]) if min(brr[0]) <= min(brr[1]) else min(brr[1])

print(min_of_b)

print(np.min(brr))



3
3


In [91]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(brr[0]) if max(brr[0]) >= max(brr[1]) else max(brr[1])

print(max_of_b)
print(np.max(brr))

8
8


In [92]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(brr[0]) + sum(brr[1])) / (len(brr[0]) + len(brr[1]))

print(mean_of_b)
print(np.mean(brr))

5.5
5.5


In [93]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in brr:
    for number in row:
        product_of_b *= number
print(product_of_b)
print(np.product(brr))

20160
20160


In [95]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in brr:
    for number in row:
        squares_of_b.append(number**2)
        
print(squares_of_b)
        
print(np.square(brr))


[9, 16, 25, 36, 49, 64]
[[ 9 16 25]
 [36 49 64]]


In [98]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in brr:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
print(odds_in_b)

odd_b =brr[brr % 2 == 1]

print(odd_b)



[3, 5, 7]
[3 5 7]


In [100]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in brr:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

even_b =brr[brr % 2 == 0]
print(even_b)


[4, 6, 8]
[4 6 8]


In [102]:
# Exercise 9 - print out the shape of the array b.
brr

array([[3, 4, 5],
       [6, 7, 8]])

In [103]:
# Exercise 10 - transpose the array b.
brr_t = np.transpose(brr)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [121]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
new_brr =brr.reshape(-1)
print (new_brr)

[3 4 5 6 7 8]


In [122]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
tall_brr = brr.reshape(6,1)
print(tall_brr)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# Part 3

In [124]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

crr = np.array(c)
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
print(crr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [126]:
# Exercise 1 - Find the min, max, sum, and product of c.
crr_min = np.min(crr)
crr_max = np.max(crr)
crr_sum = np.sum(crr)
crr_product = np.product(crr)

print(crr_min)
print(crr_max)
print(crr_sum)
print(crr_product)


1
9
45
362880


In [127]:
# Exercise 2 - Determine the standard deviation of c.
crr_std = np.std(crr)

print(crr_std)

2.581988897471611


In [128]:
# Exercise 3 - Determine the variance of c.
crr_var = np.var(crr)

print(crr_var)

6.666666666666667


In [129]:
# Exercise 4 - Print out the shape of the array c
print(crr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [131]:
# Exercise 5 - Transpose c and print out transposed result.
crr_t = np.transpose(crr)

print(crr_t)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [132]:
# Exercise 6 - Get the dot product of the array c with c. 
dot_pro_crr = np.dot(crr,crr)

print(dot_pro_crr)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [168]:
# Exercise 7 - Write the code necessary to sum up the result of c times

new_crr = crr * crr_t

print(new_crr)
sum_new_crr = np.sum(new_crr)

print(sum_new_crr)



[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
261


In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [169]:
p_crr = crr * crr_t
pro_new_crr = np.product(p_crr)

print(pro_new_crr)

131681894400


# part 4

In [139]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

drr = np.array(d)

print(drr)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


In [142]:
# Exercise 1 - Find the sine of all the numbers in d
drr_si = np.sin(drr)

print(drr_si)

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [144]:
# Exercise 2 - Find the cosine of all the numbers in d
drr_cos = np.cos(drr)

print(drr_cos)

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [147]:
# Exercise 3 - Find the tangent of all the numbers in d
drr_ta = np.tan(drr)

print(drr_ta)

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [149]:
# Exercise 4 - Find all the negative numbers in d
print(drr)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


In [ ]:
drr_odd = drr[drr % 2 == 1]

print(drr_odd)

In [150]:
# Exercise 5 - Find all the positive numbers in d
drr_even = drr[drr % 2 == 0]

print(drr_even)

[ 90  30   0 120 180 -90 -30 270  90   0  60  90 180]


In [152]:
# Exercise 6 - Return an array of only the unique numbers in d.
drr_uni = np.unique(drr)

print(drr_uni)


[-90 -45 -30   0  30  45  60  90 120 180 270]


In [153]:
# Exercise 7 - Determine how many unique numbers there are in d.
drr_uni.shape

(11,)

In [154]:
# Exercise 8 - Print out the shape of d.

print(drr)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


In [156]:

# Exercise 9 - Transpose and then print out the shape of d.
drr_t = np.transpose(drr)
print(drr_t)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [165]:
# Exercise 10 - Reshape d into an array of 9 x 2

drr_res = drr.reshape(-1)

print(drr_res)

drr_res = drr_res.reshape(9,2)

print(drr_res)

[ 90  30  45   0 120 180  45 -90 -30 270  90   0  60  45 -45  90 -45 180]
[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
